// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ConvertSWF() {
  return window['go']['main']['App']['ConvertSWF']();
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function LoadNitroFile(arg1) {
  return window['go']['main']['App']['LoadNitroFile'](arg1);
}

export function LoadProject(arg1) {
  return window['go']['main']['App']['LoadProject'](arg1);
}

export function OpenNitroFile() {
  return window['go']['main']['App']['OpenNitroFile']();
}

export function OpenProject() {
  return window['go']['main']['App']['OpenProject']();
}

export function RenameNitroProject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RenameNitroProject'](arg1, arg2, arg3, arg4);
}

export function SaveFileAs(arg1, arg2) {
  return window['go']['main']['App']['SaveFileAs'](arg1, arg2);
}

export function SaveNitroFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveNitroFile'](arg1, arg2, arg3);
}

export function SaveProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveProject'](arg1, arg2, arg3);
}

export function SelectMultipleSWFFiles() {
  return window['go']['main']['App']['SelectMultipleSWFFiles']();
}

export function BatchConvertSWFsToNitro(arg1) {
  return window['go']['main']['App']['BatchConvertSWFsToNitro'](arg1);
}
