// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BatchConvertSWFsToNitro(arg1:Array<string>):Promise<main.BatchConversionResult>;

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function ConvertSWF():Promise<main.NitroResponse>;

export function GetCurrentVersion():Promise<string>;

export function LoadNitroFile(arg1:string):Promise<main.NitroResponse>;

export function LoadProject(arg1:string):Promise<main.NitroResponse>;

export function OpenNitroFile():Promise<main.NitroResponse>;

export function OpenProject():Promise<main.NitroResponse>;

export function RenameNitroProject(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<main.NitroResponse>;

export function SaveFileAs(arg1:string,arg2:string):Promise<string>;

export function SaveNitroFile(arg1:string,arg2:Record<string, Array<number>>,arg3:string):Promise<string>;

export function SaveProject(arg1:string,arg2:main.RsprProject,arg3:string):Promise<string>;

export function SelectMultipleSWFFiles():Promise<Array<string>>;
