// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchConvertSWFsToNitro(arg1) {
  return window['go']['main']['App']['BatchConvertSWFsToNitro'](arg1);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ConvertSWF() {
  return window['go']['main']['App']['ConvertSWF']();
}

export function CropSprite(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CropSprite'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ExtractMultipleSprites(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExtractMultipleSprites'](arg1, arg2, arg3);
}

export function ExtractSingleSprite(arg1, arg2) {
  return window['go']['main']['App']['ExtractSingleSprite'](arg1, arg2);
}

export function ExtractSpritesheet(arg1) {
  return window['go']['main']['App']['ExtractSpritesheet'](arg1);
}

export function FlipSprite(arg1, arg2, arg3) {
  return window['go']['main']['App']['FlipSprite'](arg1, arg2, arg3);
}

export function GenerateSpriteThumbnails(arg1) {
  return window['go']['main']['App']['GenerateSpriteThumbnails'](arg1);
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetWatcherStatus() {
  return window['go']['main']['App']['GetWatcherStatus']();
}

export function LoadNitroFile(arg1) {
  return window['go']['main']['App']['LoadNitroFile'](arg1);
}

export function LoadProject(arg1) {
  return window['go']['main']['App']['LoadProject'](arg1);
}

export function OpenNitroFile() {
  return window['go']['main']['App']['OpenNitroFile']();
}

export function OpenProject() {
  return window['go']['main']['App']['OpenProject']();
}

export function ReadExternalFile(arg1) {
  return window['go']['main']['App']['ReadExternalFile'](arg1);
}

export function RenameNitroProject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RenameNitroProject'](arg1, arg2, arg3, arg4);
}

export function ReplaceEntireSpritesheet(arg1, arg2) {
  return window['go']['main']['App']['ReplaceEntireSpritesheet'](arg1, arg2);
}

export function ReplaceSingleSprite(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReplaceSingleSprite'](arg1, arg2, arg3);
}

export function ResizeSprite(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ResizeSprite'](arg1, arg2, arg3, arg4);
}

export function SaveFileAs(arg1, arg2) {
  return window['go']['main']['App']['SaveFileAs'](arg1, arg2);
}

export function SaveNitroFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveNitroFile'](arg1, arg2, arg3);
}

export function SaveProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveProject'](arg1, arg2, arg3);
}

export function SelectMultipleSWFFiles() {
  return window['go']['main']['App']['SelectMultipleSWFFiles']();
}

export function StartWatchingSpriteDirectory(arg1, arg2) {
  return window['go']['main']['App']['StartWatchingSpriteDirectory'](arg1, arg2);
}

export function StopWatchingSpriteDirectory() {
  return window['go']['main']['App']['StopWatchingSpriteDirectory']();
}
